//imports
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

//Sanity Data Queries

//the homepage function
export default function Home() {
  return (
    <div className={styles.container}>
      <Head
      // Let's try and get this through sanity
      >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>This will be the relish website</h3>
        <h3>Hello World</h3>
      </main>
    </div>
  );
}

//Get Sanity Data here: add to this function, no need to create a new one.
